// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzqkazppbpwbirsihpcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6cWthenBwYnB3Ymlyc2locGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMzI1NDYsImV4cCI6MjA0OTkwODU0Nn0.LrdU_PBEN9Gfv_noHmIQZEi7jd9ySSbseB4ui7KfcBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);